-- 새 AI 공개, 가격 변경, 무료 범위 변경을 자동 기록합니다.
create table if not exists public.tool_updates (
  id bigint generated by default as identity primary key,
  tool_id text not null references public.tools(id) on delete cascade,
  update_type text not null check (update_type in ('new_tool', 'price_change', 'free_limit_change')),
  title text not null,
  summary text,
  old_value text,
  new_value text,
  created_at timestamptz not null default now()
);

create index if not exists tool_updates_created_at_idx
  on public.tool_updates(created_at desc);
create index if not exists tool_updates_tool_id_idx
  on public.tool_updates(tool_id, created_at desc);

alter table public.tool_updates enable row level security;
drop policy if exists "Public tool updates are readable" on public.tool_updates;
create policy "Public tool updates are readable"
  on public.tool_updates for select
  using (true);

grant select on public.tool_updates to anon, authenticated;
revoke insert, update, delete on public.tool_updates from anon, authenticated;

create or replace function public.capture_tool_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    if new.is_published then
      insert into public.tool_updates (tool_id, update_type, title, summary, new_value)
      values (
        new.id,
        'new_tool',
        '새 AI 등록 · ' || new.name,
        '가격·한국어·난이도 정보를 확인하고 비교해 보세요.',
        new.price
      );
    end if;
    return new;
  end if;

  if not old.is_published and new.is_published then
    insert into public.tool_updates (tool_id, update_type, title, summary, new_value)
    values (
      new.id,
      'new_tool',
      '새 AI 공개 · ' || new.name,
      '새로 공개된 AI의 상세 정보와 활용 예시를 확인해 보세요.',
      new.price
    );
  end if;

  if new.is_published and old.price is distinct from new.price then
    insert into public.tool_updates (tool_id, update_type, title, summary, old_value, new_value)
    values (
      new.id,
      'price_change',
      new.name || ' 가격 정보 변경',
      '결제 전에 공식 사이트에서 최신 가격과 포함 기능을 확인하세요.',
      old.price,
      new.price
    );
  end if;

  if new.is_published and old.free_limit is distinct from new.free_limit then
    insert into public.tool_updates (tool_id, update_type, title, summary, old_value, new_value)
    values (
      new.id,
      'free_limit_change',
      new.name || ' 무료 사용 범위 변경',
      '무료 제공량과 사용 조건을 다시 확인해 보세요.',
      old.free_limit,
      new.free_limit
    );
  end if;

  return new;
end;
$$;

drop trigger if exists tools_capture_update on public.tools;
create trigger tools_capture_update
after insert or update of is_published, price, free_limit
on public.tools
for each row execute function public.capture_tool_update();
