-- 개인정보 없이 AI 도구 인기도를 집계합니다.
-- 같은 브라우저의 같은 도구·행동은 하루에 한 번만 반영됩니다.

create table if not exists public.tool_popularity_events (
  id bigint generated by default as identity primary key,
  tool_id text not null check (char_length(tool_id) between 1 and 100),
  event_type text not null check (event_type in ('view', 'save', 'compare')),
  visitor_id text not null check (char_length(visitor_id) between 8 and 100),
  occurred_on date not null default (timezone('utc', now())::date),
  created_at timestamptz not null default now(),
  unique (tool_id, event_type, visitor_id, occurred_on)
);

alter table public.tool_popularity_events enable row level security;
revoke all on public.tool_popularity_events from anon, authenticated;

create or replace function public.record_tool_event(
  p_tool_id text,
  p_event_type text,
  p_visitor_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_event_type not in ('view', 'save', 'compare') then
    raise exception 'invalid event type';
  end if;
  if char_length(trim(p_tool_id)) not between 1 and 100
     or char_length(trim(p_visitor_id)) not between 8 and 100 then
    raise exception 'invalid event payload';
  end if;

  insert into public.tool_popularity_events (tool_id, event_type, visitor_id)
  values (trim(p_tool_id), p_event_type, trim(p_visitor_id))
  on conflict (tool_id, event_type, visitor_id, occurred_on) do nothing;
end;
$$;

create or replace function public.get_tool_popularity()
returns table (
  tool_id text,
  views bigint,
  saves bigint,
  compares bigint,
  score bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    event.tool_id,
    count(*) filter (where event.event_type = 'view') as views,
    count(*) filter (where event.event_type = 'save') as saves,
    count(*) filter (where event.event_type = 'compare') as compares,
    count(*) filter (where event.event_type = 'view')
      + count(*) filter (where event.event_type = 'save') * 3
      + count(*) filter (where event.event_type = 'compare') * 2 as score
  from public.tool_popularity_events event
  where event.occurred_on >= (timezone('utc', now())::date - 29)
  group by event.tool_id
  order by score desc, views desc;
$$;

revoke all on function public.record_tool_event(text, text, text) from public;
revoke all on function public.get_tool_popularity() from public;
grant execute on function public.record_tool_event(text, text, text) to anon, authenticated;
grant execute on function public.get_tool_popularity() to anon, authenticated;
